# Exported from Render on 2025-05-28T11:14:27Z
services:
- type: web
  name: HappyBot
  runtime: python
  repo: https://github.com/3RLI3/HappyBot
  plan: free
  envVars:
  - key: TELEGRAM_TOKEN
    sync: false
  - key: SEA_LION_API_KEY
    sync: false
  - key: REDIS_URL
    sync: false
  region: singapore
  buildCommand: pip install -r requirements.txt
  startCommand: python3 -m app.telegram_bot
  autoDeployTrigger: commit
version: "1"
